### ISSUE TITLE
Blocking connections not from cloudflare

### ISSUE THREAD

**Issue by aseques** [ergin/nginx-cloudflare-real-ip#2]
This system works fine to add the source ip to the apache logs, the problem is that after this you can't block the traffic not comming from cloudflare because it's identified with the real ip. Have you accomplished this?

**Comment by Nottt** [comment]
What do you mean block the traffic not coming from cloudflare? 

Have you tried running:

 ```
ufw allow from IP/RANGE to any port 80
ufw allow from IP/RANGE to any port 443
```
This would allow only cloudflare IP's to connect to port 80 and 443, assuming you are running your website in those ports of course.

If you delete the firewall rules allowing port 80 and 443, then your server would not respond to anyone in those ports if not coming from cloudflare IP's.

**Comment by aseques** [comment]
I prefer not to rely on the firewall to block the connections, I already have another firewall, and yet another layer to mantain makes things difficult.
I found another solution at stackoverflow that allows both, I'll paste into another issue
